// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VolumePruneHandlerFunc turns a function with the right signature into a volume prune handler
type VolumePruneHandlerFunc func(VolumePruneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VolumePruneHandlerFunc) Handle(params VolumePruneParams) middleware.Responder {
	return fn(params)
}

// VolumePruneHandler interface for that can handle valid volume prune params
type VolumePruneHandler interface {
	Handle(VolumePruneParams) middleware.Responder
}

// NewVolumePrune creates a new http.Handler for the volume prune operation
func NewVolumePrune(ctx *middleware.Context, handler VolumePruneHandler) *VolumePrune {
	return &VolumePrune{Context: ctx, Handler: handler}
}

/* VolumePrune swagger:route POST /volumes/prune Volume volumePrune

Delete unused volumes

*/
type VolumePrune struct {
	Context *middleware.Context
	Handler VolumePruneHandler
}

func (o *VolumePrune) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVolumePruneParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// VolumePruneOKBody VolumePruneResponse
//
// swagger:model VolumePruneOKBody
type VolumePruneOKBody struct {

	// Disk space reclaimed in bytes
	SpaceReclaimed int64 `json:"SpaceReclaimed,omitempty"`

	// Volumes that were deleted
	VolumesDeleted []string `json:"VolumesDeleted"`
}

// Validate validates this volume prune o k body
func (o *VolumePruneOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this volume prune o k body based on context it is used
func (o *VolumePruneOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *VolumePruneOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *VolumePruneOKBody) UnmarshalBinary(b []byte) error {
	var res VolumePruneOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
