// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package exec

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bhojpur/host/pkg/machine/models"
)

// ExecStartOKCode is the HTTP code returned for type ExecStartOK
const ExecStartOKCode int = 200

/*ExecStartOK No error

swagger:response execStartOK
*/
type ExecStartOK struct {
}

// NewExecStartOK creates ExecStartOK with default headers values
func NewExecStartOK() *ExecStartOK {

	return &ExecStartOK{}
}

// WriteResponse to the client
func (o *ExecStartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ExecStartNotFoundCode is the HTTP code returned for type ExecStartNotFound
const ExecStartNotFoundCode int = 404

/*ExecStartNotFound No such exec instance

swagger:response execStartNotFound
*/
type ExecStartNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewExecStartNotFound creates ExecStartNotFound with default headers values
func NewExecStartNotFound() *ExecStartNotFound {

	return &ExecStartNotFound{}
}

// WithPayload adds the payload to the exec start not found response
func (o *ExecStartNotFound) WithPayload(payload *models.ErrorResponse) *ExecStartNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the exec start not found response
func (o *ExecStartNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExecStartNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExecStartConflictCode is the HTTP code returned for type ExecStartConflict
const ExecStartConflictCode int = 409

/*ExecStartConflict Container is stopped or paused

swagger:response execStartConflict
*/
type ExecStartConflict struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewExecStartConflict creates ExecStartConflict with default headers values
func NewExecStartConflict() *ExecStartConflict {

	return &ExecStartConflict{}
}

// WithPayload adds the payload to the exec start conflict response
func (o *ExecStartConflict) WithPayload(payload *models.ErrorResponse) *ExecStartConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the exec start conflict response
func (o *ExecStartConflict) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExecStartConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
