// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bhojpur/host/pkg/machine/models"
)

// ContainerPruneOKCode is the HTTP code returned for type ContainerPruneOK
const ContainerPruneOKCode int = 200

/*ContainerPruneOK No error

swagger:response containerPruneOK
*/
type ContainerPruneOK struct {

	/*
	  In: Body
	*/
	Payload *ContainerPruneOKBody `json:"body,omitempty"`
}

// NewContainerPruneOK creates ContainerPruneOK with default headers values
func NewContainerPruneOK() *ContainerPruneOK {

	return &ContainerPruneOK{}
}

// WithPayload adds the payload to the container prune o k response
func (o *ContainerPruneOK) WithPayload(payload *ContainerPruneOKBody) *ContainerPruneOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container prune o k response
func (o *ContainerPruneOK) SetPayload(payload *ContainerPruneOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerPruneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ContainerPruneInternalServerErrorCode is the HTTP code returned for type ContainerPruneInternalServerError
const ContainerPruneInternalServerErrorCode int = 500

/*ContainerPruneInternalServerError Server error

swagger:response containerPruneInternalServerError
*/
type ContainerPruneInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewContainerPruneInternalServerError creates ContainerPruneInternalServerError with default headers values
func NewContainerPruneInternalServerError() *ContainerPruneInternalServerError {

	return &ContainerPruneInternalServerError{}
}

// WithPayload adds the payload to the container prune internal server error response
func (o *ContainerPruneInternalServerError) WithPayload(payload *models.ErrorResponse) *ContainerPruneInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container prune internal server error response
func (o *ContainerPruneInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerPruneInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
