// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bhojpur/host/pkg/machine/models"
)

// ContainerUpdateOKCode is the HTTP code returned for type ContainerUpdateOK
const ContainerUpdateOKCode int = 200

/*ContainerUpdateOK The container has been updated.

swagger:response containerUpdateOK
*/
type ContainerUpdateOK struct {

	/*
	  In: Body
	*/
	Payload *ContainerUpdateOKBody `json:"body,omitempty"`
}

// NewContainerUpdateOK creates ContainerUpdateOK with default headers values
func NewContainerUpdateOK() *ContainerUpdateOK {

	return &ContainerUpdateOK{}
}

// WithPayload adds the payload to the container update o k response
func (o *ContainerUpdateOK) WithPayload(payload *ContainerUpdateOKBody) *ContainerUpdateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container update o k response
func (o *ContainerUpdateOK) SetPayload(payload *ContainerUpdateOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ContainerUpdateNotFoundCode is the HTTP code returned for type ContainerUpdateNotFound
const ContainerUpdateNotFoundCode int = 404

/*ContainerUpdateNotFound no such container

swagger:response containerUpdateNotFound
*/
type ContainerUpdateNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewContainerUpdateNotFound creates ContainerUpdateNotFound with default headers values
func NewContainerUpdateNotFound() *ContainerUpdateNotFound {

	return &ContainerUpdateNotFound{}
}

// WithPayload adds the payload to the container update not found response
func (o *ContainerUpdateNotFound) WithPayload(payload *models.ErrorResponse) *ContainerUpdateNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container update not found response
func (o *ContainerUpdateNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerUpdateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ContainerUpdateInternalServerErrorCode is the HTTP code returned for type ContainerUpdateInternalServerError
const ContainerUpdateInternalServerErrorCode int = 500

/*ContainerUpdateInternalServerError server error

swagger:response containerUpdateInternalServerError
*/
type ContainerUpdateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewContainerUpdateInternalServerError creates ContainerUpdateInternalServerError with default headers values
func NewContainerUpdateInternalServerError() *ContainerUpdateInternalServerError {

	return &ContainerUpdateInternalServerError{}
}

// WithPayload adds the payload to the container update internal server error response
func (o *ContainerUpdateInternalServerError) WithPayload(payload *models.ErrorResponse) *ContainerUpdateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container update internal server error response
func (o *ContainerUpdateInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerUpdateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
