// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bhojpur/host/pkg/machine/models"
)

// ContainerWaitOKCode is the HTTP code returned for type ContainerWaitOK
const ContainerWaitOKCode int = 200

/*ContainerWaitOK The container has exit.

swagger:response containerWaitOK
*/
type ContainerWaitOK struct {

	/*
	  In: Body
	*/
	Payload *models.ContainerWaitOKBody `json:"body,omitempty"`
}

// NewContainerWaitOK creates ContainerWaitOK with default headers values
func NewContainerWaitOK() *ContainerWaitOK {

	return &ContainerWaitOK{}
}

// WithPayload adds the payload to the container wait o k response
func (o *ContainerWaitOK) WithPayload(payload *models.ContainerWaitOKBody) *ContainerWaitOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container wait o k response
func (o *ContainerWaitOK) SetPayload(payload *models.ContainerWaitOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerWaitOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ContainerWaitBadRequestCode is the HTTP code returned for type ContainerWaitBadRequest
const ContainerWaitBadRequestCode int = 400

/*ContainerWaitBadRequest bad parameter

swagger:response containerWaitBadRequest
*/
type ContainerWaitBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewContainerWaitBadRequest creates ContainerWaitBadRequest with default headers values
func NewContainerWaitBadRequest() *ContainerWaitBadRequest {

	return &ContainerWaitBadRequest{}
}

// WithPayload adds the payload to the container wait bad request response
func (o *ContainerWaitBadRequest) WithPayload(payload *models.ErrorResponse) *ContainerWaitBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container wait bad request response
func (o *ContainerWaitBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerWaitBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ContainerWaitNotFoundCode is the HTTP code returned for type ContainerWaitNotFound
const ContainerWaitNotFoundCode int = 404

/*ContainerWaitNotFound no such container

swagger:response containerWaitNotFound
*/
type ContainerWaitNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewContainerWaitNotFound creates ContainerWaitNotFound with default headers values
func NewContainerWaitNotFound() *ContainerWaitNotFound {

	return &ContainerWaitNotFound{}
}

// WithPayload adds the payload to the container wait not found response
func (o *ContainerWaitNotFound) WithPayload(payload *models.ErrorResponse) *ContainerWaitNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container wait not found response
func (o *ContainerWaitNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerWaitNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ContainerWaitInternalServerErrorCode is the HTTP code returned for type ContainerWaitInternalServerError
const ContainerWaitInternalServerErrorCode int = 500

/*ContainerWaitInternalServerError server error

swagger:response containerWaitInternalServerError
*/
type ContainerWaitInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewContainerWaitInternalServerError creates ContainerWaitInternalServerError with default headers values
func NewContainerWaitInternalServerError() *ContainerWaitInternalServerError {

	return &ContainerWaitInternalServerError{}
}

// WithPayload adds the payload to the container wait internal server error response
func (o *ContainerWaitInternalServerError) WithPayload(payload *models.ErrorResponse) *ContainerWaitInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container wait internal server error response
func (o *ContainerWaitInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerWaitInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
