// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BuildCache build cache
//
// swagger:model BuildCache
type BuildCache struct {

	// Date and time at which the build cache was created in
	// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
	//
	// Example: 2016-08-18T10:44:24.496525531Z
	CreatedAt string `json:"CreatedAt,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// ID
	ID string `json:"ID,omitempty"`

	// in use
	InUse bool `json:"InUse,omitempty"`

	// Date and time at which the build cache was last used in
	// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
	//
	// Example: 2017-08-09T07:09:37.632105588Z
	LastUsedAt *string `json:"LastUsedAt,omitempty"`

	// parent
	Parent string `json:"Parent,omitempty"`

	// shared
	Shared bool `json:"Shared,omitempty"`

	// Amount of disk space used by the build cache (in bytes).
	//
	Size int64 `json:"Size,omitempty"`

	// type
	Type string `json:"Type,omitempty"`

	// usage count
	UsageCount int64 `json:"UsageCount,omitempty"`
}

// Validate validates this build cache
func (m *BuildCache) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this build cache based on context it is used
func (m *BuildCache) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BuildCache) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildCache) UnmarshalBinary(b []byte) error {
	var res BuildCache
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
