// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigSpec config spec
//
// swagger:model ConfigSpec
type ConfigSpec struct {

	// Base64-url-safe-encoded ([RFC 4648](https://tools.ietf.org/html/rfc4648#section-5))
	// config data.
	//
	Data string `json:"Data,omitempty"`

	// User-defined key/value metadata.
	Labels map[string]string `json:"Labels,omitempty"`

	// User-defined name of the config.
	Name string `json:"Name,omitempty"`

	// Templating driver, if applicable
	//
	// Templating controls whether and how to evaluate the config payload as
	// a template. If no driver is set, no templating is used.
	//
	Templating *Driver `json:"Templating,omitempty"`
}

// Validate validates this config spec
func (m *ConfigSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTemplating(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigSpec) validateTemplating(formats strfmt.Registry) error {
	if swag.IsZero(m.Templating) { // not required
		return nil
	}

	if m.Templating != nil {
		if err := m.Templating.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Templating")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Templating")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this config spec based on the context it is used
func (m *ConfigSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTemplating(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigSpec) contextValidateTemplating(ctx context.Context, formats strfmt.Registry) error {

	if m.Templating != nil {
		if err := m.Templating.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Templating")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Templating")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigSpec) UnmarshalBinary(b []byte) error {
	var res ConfigSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
