// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bhojpur/host/pkg/machine/models"
)

// ImageTagReader is a Reader for the ImageTag structure.
type ImageTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImageTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewImageTagCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewImageTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewImageTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewImageTagConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewImageTagInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewImageTagCreated creates a ImageTagCreated with default headers values
func NewImageTagCreated() *ImageTagCreated {
	return &ImageTagCreated{}
}

/* ImageTagCreated describes a response with status code 201, with default header values.

No error
*/
type ImageTagCreated struct {
}

func (o *ImageTagCreated) Error() string {
	return fmt.Sprintf("[POST /images/{name}/tag][%d] imageTagCreated ", 201)
}

func (o *ImageTagCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImageTagBadRequest creates a ImageTagBadRequest with default headers values
func NewImageTagBadRequest() *ImageTagBadRequest {
	return &ImageTagBadRequest{}
}

/* ImageTagBadRequest describes a response with status code 400, with default header values.

Bad parameter
*/
type ImageTagBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *ImageTagBadRequest) Error() string {
	return fmt.Sprintf("[POST /images/{name}/tag][%d] imageTagBadRequest  %+v", 400, o.Payload)
}
func (o *ImageTagBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ImageTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageTagNotFound creates a ImageTagNotFound with default headers values
func NewImageTagNotFound() *ImageTagNotFound {
	return &ImageTagNotFound{}
}

/* ImageTagNotFound describes a response with status code 404, with default header values.

No such image
*/
type ImageTagNotFound struct {
	Payload *models.ErrorResponse
}

func (o *ImageTagNotFound) Error() string {
	return fmt.Sprintf("[POST /images/{name}/tag][%d] imageTagNotFound  %+v", 404, o.Payload)
}
func (o *ImageTagNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ImageTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageTagConflict creates a ImageTagConflict with default headers values
func NewImageTagConflict() *ImageTagConflict {
	return &ImageTagConflict{}
}

/* ImageTagConflict describes a response with status code 409, with default header values.

Conflict
*/
type ImageTagConflict struct {
	Payload *models.ErrorResponse
}

func (o *ImageTagConflict) Error() string {
	return fmt.Sprintf("[POST /images/{name}/tag][%d] imageTagConflict  %+v", 409, o.Payload)
}
func (o *ImageTagConflict) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ImageTagConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageTagInternalServerError creates a ImageTagInternalServerError with default headers values
func NewImageTagInternalServerError() *ImageTagInternalServerError {
	return &ImageTagInternalServerError{}
}

/* ImageTagInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ImageTagInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ImageTagInternalServerError) Error() string {
	return fmt.Sprintf("[POST /images/{name}/tag][%d] imageTagInternalServerError  %+v", 500, o.Payload)
}
func (o *ImageTagInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ImageTagInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
