// Code generated by go-swagger; DO NOT EDIT.
// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Package server Bhojpur Host
//
//  The Bhojpur Host machine API is an HTTP API served by the Bhojpur Host engine.
//  It is the API that Bhojpur Host client uses to communicate with the Bhojpur Host
//  machine, so everything the Bhojpur Host client can do can be done with this API.
//
//  Most of the client's commands map directly to API endpoints (e.g. `hostutl ps`
//  is `GET /containers/json`). The notable exception is running containers, which
//  consists of several API calls.
//
//  # Errors
//
//  The API uses standard HTTP status codes to indicate the success or failure
//  of the API call. The body of the response will be JSON in the following
//  format:
//
//  ```
//  {
//    "message": "page not found"
//  }
//  ```
//
//  # Versioning
//
//  The API is usually changed in each release, so API calls are versioned to
//  ensure that clients don't break. To lock to a specific version of the API,
//  you prefix the URL with its version, for example, call `/v1.30/info` to use
//  the v1.30 version of the `/info` endpoint. If the API version specified in
//  the URL is not supported by the daemon, a HTTP `400 Bad Request` error message
//  is returned.
//
//  If you omit the version-prefix, the current version of the API (v1.42) is used.
//  For example, calling `/info` is the same as calling `/v1.42/info`. Using the
//  API without a version-prefix is deprecated and will be removed in a future release.
//
//  Bhojpur Host releases in the near future should support this version of the API,
//  so your client will continue to work even if it is talking to a newer Bhojpur Host.
//
//  The API uses an open schema model, which means server may add extra properties
//  to responses. Likewise, the server will ignore any extra query parameters and
//  request body properties. When you write clients, you need to ignore additional
//  properties in responses to ensure they do not break when talking to newer
//  daemons.
//
//
//  # Authentication
//
//  Authentication for registries is handled client side. The client has to send
//  authentication details to various endpoints that need to communicate with
//  registries, such as `POST /images/(name)/push`. These are sent as
//  `X-Registry-Auth` header as a [base64url encoded](https://tools.ietf.org/html/rfc4648#section-5)
//  (JSON) string with the following structure:
//
//  ```
//  {
//    "username": "string",
//    "password": "string",
//    "email": "string",
//    "serveraddress": "string"
//  }
//  ```
//
//  The `serveraddress` is a domain/IP without a protocol. Throughout this
//  structure, double quotes are required.
//
//  If you have already got an identity token from the [`/auth` endpoint](#operation/SystemAuth),
//  you can just pass this instead of credentials:
//
//  ```
//  {
//    "identitytoken": "9cbaf023786cd7..."
//  }
//  ```
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /v1.42
//  Version: 1.42
//
//  Consumes:
//    - application/octet-stream
//    - application/json
//    - application/x-tar
//    - text/plain
//
//  Produces:
//    - application/octet-stream
//    - application/vnd.bhojpur.raw-stream
//    - application/json
//    - application/x-tar
//    - text/plain
//
// swagger:meta
package server
