// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package exec

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewContainerExecParams creates a new ContainerExecParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContainerExecParams() *ContainerExecParams {
	return &ContainerExecParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewContainerExecParamsWithTimeout creates a new ContainerExecParams object
// with the ability to set a timeout on a request.
func NewContainerExecParamsWithTimeout(timeout time.Duration) *ContainerExecParams {
	return &ContainerExecParams{
		timeout: timeout,
	}
}

// NewContainerExecParamsWithContext creates a new ContainerExecParams object
// with the ability to set a context for a request.
func NewContainerExecParamsWithContext(ctx context.Context) *ContainerExecParams {
	return &ContainerExecParams{
		Context: ctx,
	}
}

// NewContainerExecParamsWithHTTPClient creates a new ContainerExecParams object
// with the ability to set a custom HTTPClient for a request.
func NewContainerExecParamsWithHTTPClient(client *http.Client) *ContainerExecParams {
	return &ContainerExecParams{
		HTTPClient: client,
	}
}

/* ContainerExecParams contains all the parameters to send to the API endpoint
   for the container exec operation.

   Typically these are written to a http.Request.
*/
type ContainerExecParams struct {

	/* ExecConfig.

	   Exec configuration
	*/
	ExecConfig ContainerExecBody

	/* ID.

	   ID or name of container
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the container exec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContainerExecParams) WithDefaults() *ContainerExecParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the container exec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContainerExecParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the container exec params
func (o *ContainerExecParams) WithTimeout(timeout time.Duration) *ContainerExecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the container exec params
func (o *ContainerExecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the container exec params
func (o *ContainerExecParams) WithContext(ctx context.Context) *ContainerExecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the container exec params
func (o *ContainerExecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the container exec params
func (o *ContainerExecParams) WithHTTPClient(client *http.Client) *ContainerExecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the container exec params
func (o *ContainerExecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExecConfig adds the execConfig to the container exec params
func (o *ContainerExecParams) WithExecConfig(execConfig ContainerExecBody) *ContainerExecParams {
	o.SetExecConfig(execConfig)
	return o
}

// SetExecConfig adds the execConfig to the container exec params
func (o *ContainerExecParams) SetExecConfig(execConfig ContainerExecBody) {
	o.ExecConfig = execConfig
}

// WithID adds the id to the container exec params
func (o *ContainerExecParams) WithID(id string) *ContainerExecParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the container exec params
func (o *ContainerExecParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ContainerExecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.ExecConfig); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
