// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bhojpur/host/pkg/machine/models"
)

// PluginSetNoContentCode is the HTTP code returned for type PluginSetNoContent
const PluginSetNoContentCode int = 204

/*PluginSetNoContent No error

swagger:response pluginSetNoContent
*/
type PluginSetNoContent struct {
}

// NewPluginSetNoContent creates PluginSetNoContent with default headers values
func NewPluginSetNoContent() *PluginSetNoContent {

	return &PluginSetNoContent{}
}

// WriteResponse to the client
func (o *PluginSetNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PluginSetNotFoundCode is the HTTP code returned for type PluginSetNotFound
const PluginSetNotFoundCode int = 404

/*PluginSetNotFound Plugin not installed

swagger:response pluginSetNotFound
*/
type PluginSetNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPluginSetNotFound creates PluginSetNotFound with default headers values
func NewPluginSetNotFound() *PluginSetNotFound {

	return &PluginSetNotFound{}
}

// WithPayload adds the payload to the plugin set not found response
func (o *PluginSetNotFound) WithPayload(payload *models.ErrorResponse) *PluginSetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the plugin set not found response
func (o *PluginSetNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PluginSetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PluginSetInternalServerErrorCode is the HTTP code returned for type PluginSetInternalServerError
const PluginSetInternalServerErrorCode int = 500

/*PluginSetInternalServerError Server error

swagger:response pluginSetInternalServerError
*/
type PluginSetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPluginSetInternalServerError creates PluginSetInternalServerError with default headers values
func NewPluginSetInternalServerError() *PluginSetInternalServerError {

	return &PluginSetInternalServerError{}
}

// WithPayload adds the payload to the plugin set internal server error response
func (o *PluginSetInternalServerError) WithPayload(payload *models.ErrorResponse) *PluginSetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the plugin set internal server error response
func (o *PluginSetInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PluginSetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
