// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPluginPrivilegesParams creates a new GetPluginPrivilegesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPluginPrivilegesParams() *GetPluginPrivilegesParams {
	return &GetPluginPrivilegesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPluginPrivilegesParamsWithTimeout creates a new GetPluginPrivilegesParams object
// with the ability to set a timeout on a request.
func NewGetPluginPrivilegesParamsWithTimeout(timeout time.Duration) *GetPluginPrivilegesParams {
	return &GetPluginPrivilegesParams{
		timeout: timeout,
	}
}

// NewGetPluginPrivilegesParamsWithContext creates a new GetPluginPrivilegesParams object
// with the ability to set a context for a request.
func NewGetPluginPrivilegesParamsWithContext(ctx context.Context) *GetPluginPrivilegesParams {
	return &GetPluginPrivilegesParams{
		Context: ctx,
	}
}

// NewGetPluginPrivilegesParamsWithHTTPClient creates a new GetPluginPrivilegesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPluginPrivilegesParamsWithHTTPClient(client *http.Client) *GetPluginPrivilegesParams {
	return &GetPluginPrivilegesParams{
		HTTPClient: client,
	}
}

/* GetPluginPrivilegesParams contains all the parameters to send to the API endpoint
   for the get plugin privileges operation.

   Typically these are written to a http.Request.
*/
type GetPluginPrivilegesParams struct {

	/* Remote.

	     The name of the plugin. The `:latest` tag is optional, and is the
	default if omitted.

	*/
	Remote string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get plugin privileges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPluginPrivilegesParams) WithDefaults() *GetPluginPrivilegesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get plugin privileges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPluginPrivilegesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get plugin privileges params
func (o *GetPluginPrivilegesParams) WithTimeout(timeout time.Duration) *GetPluginPrivilegesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plugin privileges params
func (o *GetPluginPrivilegesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plugin privileges params
func (o *GetPluginPrivilegesParams) WithContext(ctx context.Context) *GetPluginPrivilegesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plugin privileges params
func (o *GetPluginPrivilegesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plugin privileges params
func (o *GetPluginPrivilegesParams) WithHTTPClient(client *http.Client) *GetPluginPrivilegesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plugin privileges params
func (o *GetPluginPrivilegesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRemote adds the remote to the get plugin privileges params
func (o *GetPluginPrivilegesParams) WithRemote(remote string) *GetPluginPrivilegesParams {
	o.SetRemote(remote)
	return o
}

// SetRemote adds the remote to the get plugin privileges params
func (o *GetPluginPrivilegesParams) SetRemote(remote string) {
	o.Remote = remote
}

// WriteToRequest writes these params to a swagger request
func (o *GetPluginPrivilegesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param remote
	qrRemote := o.Remote
	qRemote := qrRemote
	if qRemote != "" {

		if err := r.SetQueryParam("remote", qRemote); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
