// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bhojpur/host/pkg/machine/models"
)

// SystemVersionOKCode is the HTTP code returned for type SystemVersionOK
const SystemVersionOKCode int = 200

/*SystemVersionOK no error

swagger:response systemVersionOK
*/
type SystemVersionOK struct {

	/*
	  In: Body
	*/
	Payload *models.SystemVersion `json:"body,omitempty"`
}

// NewSystemVersionOK creates SystemVersionOK with default headers values
func NewSystemVersionOK() *SystemVersionOK {

	return &SystemVersionOK{}
}

// WithPayload adds the payload to the system version o k response
func (o *SystemVersionOK) WithPayload(payload *models.SystemVersion) *SystemVersionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the system version o k response
func (o *SystemVersionOK) SetPayload(payload *models.SystemVersion) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SystemVersionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SystemVersionInternalServerErrorCode is the HTTP code returned for type SystemVersionInternalServerError
const SystemVersionInternalServerErrorCode int = 500

/*SystemVersionInternalServerError server error

swagger:response systemVersionInternalServerError
*/
type SystemVersionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSystemVersionInternalServerError creates SystemVersionInternalServerError with default headers values
func NewSystemVersionInternalServerError() *SystemVersionInternalServerError {

	return &SystemVersionInternalServerError{}
}

// WithPayload adds the payload to the system version internal server error response
func (o *SystemVersionInternalServerError) WithPayload(payload *models.ErrorResponse) *SystemVersionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the system version internal server error response
func (o *SystemVersionInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SystemVersionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
