// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bhojpur/host/pkg/machine/models"
)

// ConfigListOKCode is the HTTP code returned for type ConfigListOK
const ConfigListOKCode int = 200

/*ConfigListOK no error

swagger:response configListOK
*/
type ConfigListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Config `json:"body,omitempty"`
}

// NewConfigListOK creates ConfigListOK with default headers values
func NewConfigListOK() *ConfigListOK {

	return &ConfigListOK{}
}

// WithPayload adds the payload to the config list o k response
func (o *ConfigListOK) WithPayload(payload []*models.Config) *ConfigListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the config list o k response
func (o *ConfigListOK) SetPayload(payload []*models.Config) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfigListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Config, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ConfigListInternalServerErrorCode is the HTTP code returned for type ConfigListInternalServerError
const ConfigListInternalServerErrorCode int = 500

/*ConfigListInternalServerError server error

swagger:response configListInternalServerError
*/
type ConfigListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewConfigListInternalServerError creates ConfigListInternalServerError with default headers values
func NewConfigListInternalServerError() *ConfigListInternalServerError {

	return &ConfigListInternalServerError{}
}

// WithPayload adds the payload to the config list internal server error response
func (o *ConfigListInternalServerError) WithPayload(payload *models.ErrorResponse) *ConfigListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the config list internal server error response
func (o *ConfigListInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfigListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ConfigListServiceUnavailableCode is the HTTP code returned for type ConfigListServiceUnavailable
const ConfigListServiceUnavailableCode int = 503

/*ConfigListServiceUnavailable node is not part of a swarm

swagger:response configListServiceUnavailable
*/
type ConfigListServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewConfigListServiceUnavailable creates ConfigListServiceUnavailable with default headers values
func NewConfigListServiceUnavailable() *ConfigListServiceUnavailable {

	return &ConfigListServiceUnavailable{}
}

// WithPayload adds the payload to the config list service unavailable response
func (o *ConfigListServiceUnavailable) WithPayload(payload *models.ErrorResponse) *ConfigListServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the config list service unavailable response
func (o *ConfigListServiceUnavailable) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfigListServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
